<?php
if (!defined('FREEPBX_IS_AUTH')) { die('No direct script access allowed'); }

$H323 = array(
'port'=>"1720",
'bindaddr'=>"1.2.3.4",
'tos_audio'=>"ef",
'cos_audio'=>"5",
'amaflags'=>"default",
'accountcode'=>"3ABXO3",
'codecs'=>1,
'codecs_allow' => array('ulaw_allow'     => 0,'alaw_allow'     => 0,'gsm_allow'      => 0,'siren14_allow'  => 0,'lpc10_allow'    => 0,
			'speex_allow'    => 0,'g722_allow'     => 0,'adpcm_allow'    => 0,'siren7_allow'   => 0,'g723_allow'     => 0,
			'slin_allow'     => 0,'g726_allow'     => 0,'g729_allow'     => 0,'ilbc_allow'     => 0,'g726aal2_allow' => 0),
'codecs_disallow' => array('ulaw_disallow'     => 0,'alaw_disallow'     => 0,'gsm_disallow'      => 0,'siren14_disallow'  => 0,'lpc10_disallow'    => 0,
			'speex_disallow'    => 0,'g722_disallow'     => 0,'adpcm_disallow'    => 0,'siren7_disallow'   => 0,'g723_disallow'     => 0,
			'slin_disallow'     => 0,'g726_disallow'     => 0,'g729_disallow'     => 0,'ilbc_disallow'     => 0,'g726aal2_disallow' => 0),
'dtmfmode'=>"rfc2833",
'payload_type'=>"101",
'gatekeeper'=>"DISABLE",
'allowgkrouted'=>"yes",
'acceptanonymous'=>"yes",
'userbyalias'=>"no",
'context'=>"from-trunk",
'faststart'=>"no",
'h245tunneling'=>"no",
'progress_setup'=>"3",
'progress_alert'=>"8",
'progress_audio'=>"yes",
'tunneling'=>"none",
'hold'=>"none",
'jbenable'=>"no",
'jbforce'=>"no",
'jbmaxsize'=>"200",
'jbresyncthreshold'=>"1000",
'jbimpl'=>"fixed",
'jblog'=>"no",
'commentmap' => array(
'port'			=>1,
'bindaddr'		=>1,
'tos_audio'		=>1,
'cos_audio'		=>1,
'amaflags'		=>1,
'accountcode'		=>1,
'codecs'		=>1,
'dtmfmode'		=>1,
'payload_type'		=>1,
'gatekeeper'		=>1,
'allowgkrouted'		=>1,
'acceptanonymous'	=>1,
'userbyalias'		=>1,
'context'		=>1,
'faststart'		=>1,
'h245tunneling'		=>1,
'progress_setup'	=>1,
'progress_alert'	=>1,
'progress_audio'	=>1,
'tunneling'		=>1,
'hold'			=>1,
'jbenable'		=>1,
'jbforce'		=>1,
'jbmaxsize'		=>1,
'jbresyncthreshold'	=>1,
'jbimpl'		=>1,
'jblog'			=>1
)
);

$indication_warning = ";--------------------------------------------------------------------------------;\n; Do NOT edit this file as it is auto-generated by FreePBX. All modifications to ;\n; this file must be done via the web gui. There are alternative files to make    ;\n; custom modifications, details at: http://freepbx.org/configuration_files       ;\n;--------------------------------------------------------------------------------;\n";

function GetH323DefaultSettings($H323) {
$H323['port']="1720";
$H323['bindaddr']="0.0.0.0";
$H323['tos_audio']="ef";
$H323['cos_audio']="5";
$H323['amaflags']="default";
$H323['accountcode']="lss0101";
$H323['codecs']=0;
$H323['codecs_allow']['ulaw_allow']=1;
$H323['codecs_allow']['alaw_allow']=1;
$H323['codecs_allow']['gsm_allow']=0;
$H323['codecs_allow']['siren14_allow']=1;
$H323['codecs_allow']['lpc10_allow']=0;
$H323['codecs_allow']['speex_allow']=0;
$H323['codecs_allow']['g722_allow']=0;
$H323['codecs_allow']['adpcm_allow']=0;
$H323['codecs_allow']['siren7_allow']=0;
$H323['codecs_allow']['g723_allow']=0;
$H323['codecs_allow']['slin_allow']=0;
$H323['codecs_allow']['g726_allow']=0;
$H323['codecs_allow']['g729_allow']=0;
$H323['codecs_allow']['ilbc_allow']=0;
$H323['codecs_allow']['g726aal2_allow']=0;
$H323['codecs_disallow']['ulaw_disallow']=0;
$H323['codecs_disallow']['alaw_disallow']=0;
$H323['codecs_disallow']['gsm_disallow']=0;
$H323['codecs_disallow']['siren14_disallow']=0;
$H323['codecs_disallow']['lpc10_disallow']=0;
$H323['codecs_disallow']['speex_disallow']=0;
$H323['codecs_disallow']['g722_disallow']=0;
$H323['codecs_disallow']['adpcm_disallow']=0;
$H323['codecs_disallow']['siren7_disallow']=0;
$H323['codecs_disallow']['g723_disallow']=1;
$H323['codecs_disallow']['slin_disallow']=0;
$H323['codecs_disallow']['g726_disallow']=0;
$H323['codecs_disallow']['g729_disallow']=0;
$H323['codecs_disallow']['ilbc_disallow']=0;
$H323['codecs_disallow']['g726aal2_disallow']=0;
$H323['dtmfmode']="rfc2833";
$H323['payload_type']="101";
$H323['gatekeeper']="DISABLE";
$H323['allowgkrouted']="yes";
$H323['acceptanonymous']="yes";
$H323['userbyalias']="no";
$H323['context']="from-trunk";
$H323['faststart']="no";
$H323['h245tunneling']="no";
$H323['progress_setup']="3";
$H323['progress_alert']="8";
$H323['progress_audio']="yes";
$H323['tunneling']="none";
$H323['hold']="none";
$H323['jbenable']="no";
$H323['jbforce']="no";
$H323['jbmaxsize']="200";
$H323['jbresyncthreshold']="1000";
$H323['jbimpl']="fixed";
$H323['jblog']="no";
$H323['commentmap']['port']=1;
$H323['commentmap']['bindaddr']=1;
$H323['commentmap']['tos_audio']=1;
$H323['commentmap']['cos_audio']=1;
$H323['commentmap']['amaflags']=1;
$H323['commentmap']['accountcode']=1;
$H323['commentmap']['codecs']=1;
$H323['commentmap']['dtmfmode']=1;
$H323['commentmap']['payload_type']=1;
$H323['commentmap']['gatekeeper']=1;
$H323['commentmap']['allowgkrouted']=1;
$H323['commentmap']['acceptanonymous']=1;
$H323['commentmap']['userbyalias']=1;
$H323['commentmap']['context']=1;
$H323['commentmap']['faststart']=1;
$H323['commentmap']['h245tunneling']=1;
$H323['commentmap']['progress_setup']=1;
$H323['commentmap']['progress_alert']=1;
$H323['commentmap']['progress_audio']=1;
$H323['commentmap']['tunneling']=1;
$H323['commentmap']['hold']=1;
$H323['commentmap']['jbenable']=1;
$H323['commentmap']['jbforce']=1;
$H323['commentmap']['jbmaxsize']=1;
$H323['commentmap']['jbresyncthreshold']=1;
$H323['commentmap']['jbimpl']=1;
$H323['commentmap']['jblog']=1;
return $H323;
}

function H323ValidNumber($NUM){
    if ($NUM !='' && is_numeric($NUM)){
	if (1 <=  $NUM && $NUM<=65535) return true;
	    else return false;
    }
}

function H323ValidIP($IP){
trim($IP);
if (preg_match('/^([0-9]|[0-9][0-9]|[01][0-9][0-9]|2[0-4][0-9]|25[0-5])(\.([0-9]|[0-9][0-9]|[01][0-9][0-9]|2[0-4][0-9]|25[0-5])){3}$/',$IP)) return true;
    else return false;
}

function OnClickH323Save($H323){
//	print_r($_POST);
	$options=array( "port", "bindaddr", "tos_audio", "cos_audio","amaflags","accountcode","codec_setter",
	
			"ulaw_allow","alaw_allow","gsm_allow","siren14_allow","lpc10_allow","speex_allow","g722_allow",
			"adpcm_allow","siren7_allow","g723_allow","slin_allow","g726_allow","g729_allow","ilbc_allow","g726aal2_allow",
			
			"ulaw_disallow","alaw_disallow","gsm_disallow","siren14_disallow","lpc10_disallow","speex_disallow","g722_disallow",
			"adpcm_disallow","siren7_disallow","g723_disallow","slin_disallow","g726_disallow","g729_disallow","ilbc_disallow","g726aal2_disallow",
			
			"dtmfmode","payload_type","gatekeeper","allowgkrouted",
			"acceptanonymous","userbyalias","context","progress_setup","progress_alert","progress_audio","tunneling","hold",
			"faststart","h245tunneling","jbenable","jbforce","jbmaxsize","jbresyncthreshold","jbimpl","jblog");
	foreach($options as $option){
		if (isset($_REQUEST[$option])) {
			switch(true){
			case in_array($option,array("port","payload_type","jbmaxsize","jbresyncthreshold")):
					$num=trim($_REQUEST[$option]);
					if (H323ValidNumber($num)){
						$H323[$option]=$num;
						$H323['commentmap'][$option]=0;
					}else{
						echo '<script type="text/javascript">alert("Value \"'. $num .'\" out of range parameter \"'.strtoupper($option).'\". Please check them.\n Сhanged to the default value. ");</script>';
					}
				break;
			case in_array($option,array("bindaddr")):
					$IP=trim($_REQUEST[$option]);
					if (H323ValidIP($IP)){
						$H323[$option]=$IP;
						$H323['commentmap'][$option]=0;
					}else{
						echo '<script type="text/javascript">alert("IP \"'. strtoupper($IP) .'\" incorrect value. Please check them.\n Сhanged to the default value.");</script>';
					}
				break;
			case in_array($option,array("accountcode","context")):
						$H323[$option]=$_REQUEST[$option];
						$H323['commentmap'][$option]=0;
				break;
			case in_array($option, array(	"tos_audio", "cos_audio","amaflags","dtmfmode","allowgkrouted","acceptanonymous",
							"userbyalias","progress_setup","progress_alert","progress_audio","tunneling","hold",
							"faststart","h245tunneling","jbenable","jbforce","jbimpl","jblog")):
				$H323[$option]=$_REQUEST[$option];
				$H323['commentmap'][$option]=0;
				break;
			case in_array($option, array("ulaw_allow","alaw_allow","gsm_allow","siren14_allow","lpc10_allow",
								"speex_allow","g722_allow","adpcm_allow","siren7_allow","g723_allow","slin_allow","g726_allow",
								"g729_allow","ilbc_allow","g726aal2_allow")) :
					$H323['codecs_allow'][$option]=1;
				break;
			case in_array($option, array("ulaw_disallow","alaw_disallow","gsm_disallow","siren14_disallow","lpc10_disallow",
								"speex_disallow","g722_disallow","adpcm_disallow","siren7_disallow","g723_disallow","slin_disallow",
								"g726_disallow","g729_disallow","ilbc_disallow","g726aal2_disallow")) :
					
					$H323['codecs_disallow'][$option]=1;
				break;
			case in_array($_REQUEST[$option], array("allow_all","disallow_all")):
					if ($_REQUEST[$option]=="allow_all")  { $H323['codecs']=1;} else {$H323['codecs']=0;}
					$H323['commentmap']['codecs']=0;
				break;
				
			case in_array($option,array("gatekeeper")):
					if ($_REQUEST[$option]=="DISABLE" || $_REQUEST[$option]=="DISCOVER") {
						$H323[$option]=$_REQUEST[$option];
					}elseif($_REQUEST[$option]=="IP"){
						$IP=trim($_REQUEST['ip_host']);
						if (H323ValidIP($IP)){
							$H323[$option]=$IP;
						}
					}else{
						$H323[$option]=$_REQUEST['ip_host'];
					}
					$H323['commentmap'][$option]=0;
				break;
		
		}
	    }
	}
	SetH323CurrentSettings($H323);
	return $H323;
}

function SetH323CurrentSettings($H323) {
global $amp_conf,$indication_warning;
$data=$indication_warning;
foreach ($H323['commentmap'] as $option => $value) {
	if (!$H323['commentmap'][$option]){
		 if ($option=="codecs"){
				if ($H323[$option]) {
					$data.="allow =all\n";
					foreach ($H323['codecs_disallow'] as $key => $exist){
						if ($H323['codecs_disallow'][$key]) $data.="disallow =". str_replace("_disallow","",$key) ."\n";
					}
				}else{
					$data.="disallow =all\n";
					foreach ($H323['codecs_allow'] as $key => $exist)
						if ($H323['codecs_allow'][$key]) $data.="allow =". str_replace("_allow","",$key) ."\n";
				}
		}elseif($option=="dtmfmode"){
			if (!$H323['commentmap']['payload_type']) $data.="" .$option." =".$H323[$option].":".$H323['payload_type']."\n";
			else
				$data.="" .$option." =".$H323[$option]."\n";
		}elseif($option!="payload_type"){
			$data.="" .$option." =".$H323[$option]."\n";
		}
	}
}
$file=fopen($amp_conf['ASTETCDIR'].'/h323_additional.conf','w');
if ($file) {
	fwrite($file, $data);
	fclose($file);
    }else{
	echo '<script type="text/javascript">alert("Can\'t saving H323 configurations settings");</script>';
    }
}



function GetH323CurrentSettings($H323) {
global $amp_conf;
$options=array( "port", "bindaddr", "tos_audio", "cos_audio","amaflags","accountcode","allow","disallow",
		"ulaw","alaw","gsm","siren14","lpc10","speex","g722","adpcm","siren7","g723","slin","g726","g729","ilbc","726aal2",
		"dtmfmode","gatekeeper","allowgkrouted","acceptanonymous","userbyalias","context",
		"progress_setup","progress_alert","progress_audio",
		"tunneling","hold","faststart","h245tunneling",
		"jbenable","jbforce","jbmaxsize","jbresyncthreshold","jbimpl","jblog");

$string='';
$file = fopen($amp_conf['ASTETCDIR'].'/h323_additional.conf', "r"); 
if ($file) { 
     while (!feof($file)) { 
	$string = fgets($file,1024);
	if ($string[0]!=";" && $string[0]!="\n"){
	foreach($options as $option => $value){
		$pos=strpos($string,$value);
		if($pos !== false && $pos==0 && substr($string,$pos+strlen($value),1)==' '){
			$string=preg_replace("/[\s]/","",substr($string,$pos+strlen($value)+2,strlen($string)));
			switch (true) {
			case in_array($value,array("port","jbmaxsize","jbresyncthreshold")):
				if (H323ValidNumber($string)){
					$H323[$value]=$string;
					$H323['commentmap'][$value]=0;
				}
				break;
			case in_array($value,array("bindaddr")):
				if (H323ValidIP($string)){
					$H323[$value]=$string;
					$H323['commentmap'][$value]=0;
				}
				break;
			case in_array($value,array("disallow","allow")):
				if($string=="all"){
					if($value=="disallow") {$H323['codecs']=0;} else {$H323['codecs']=1;} 
				}else{
					$H323["codecs_".$value][$string."_".$value]=1;
				}

					$H323['commentmap']['codecs']=0;
				break;
			case in_array($value,array("dtmfmode")):
					$pos=strpos($string,":");
					if($pos !== false){
						$H323[$value]=substr($string,0,$pos);
						$string=substr($string,$pos+1,strlen($string));
						if (H323ValidNumber($string)){
							$H323['payload_type']=$string;
							$H323['commentmap']['payload_type']=0;
							}
					}else{
						$H323[$value]=$string;
					}
					$H323['commentmap'][$value]=0;
				break;
			case in_array($value, array(	"tos_audio", "cos_audio","amaflags","allowgkrouted","acceptanonymous",
							"userbyalias","progress_setup","progress_alert","progress_audio","tunneling","hold",
							"faststart","h245tunneling","jbenable","jbforce","jbimpl","jblog")):
					$H323[$value]=$string;
					$H323['commentmap'][$value]=0;
				break;
			case in_array($value,array("accountcode","context")):
						$H323[$value]=$string;
						$H323['commentmap'][$value]=0;
				break;
			case in_array($value,array("gatekeeper")):
					$H323[$value]=$string;
					$H323['commentmap'][$value]=0;
				break;
			}
		}
	    }
	}
    } 
fclose($file);
}
return $H323;
}


?>
