<?php
if (!defined('FREEPBX_IS_AUTH')) { die('No direct script access allowed'); }

global $amp_conf;

$indication_warning = ";--------------------------------------------------------------------------------;\n; Do NOT edit this file as it is auto-generated by FreePBX. All modifications to ;\n; this file must be done via the web gui. There are alternative files to make    ;\n; custom modifications, details at: http://freepbx.org/configuration_files       ;\n;--------------------------------------------------------------------------------;\n";
$name_conf = "#include h323_additional.conf\n";
$found = false;

function H323InstallCheck($data){
    $pos=strpos($data,"[");
    if ($pos!==false){
        $buff=substr($data,$pos+1,strlen($data));
        $pos=strpos($buff,"]");
	if ($pos!==false){
		return false;
	}else return true;
    }else return true;
}

function H323GetParameter($parameter){
$options=array(	"port","bindaddr", "tos_audio", "cos_audio","amaflags","accountcode","allow","disallow",
		"dtmfmode","gatekeeper","allowgkrouted","acceptanonymous","userbyalias","context",
		"progress_setup","progress_alert","progress_audio",
		"tunneling","hold","faststart","h245tunneling",
		"jbenable","jbforce","jbmaxsize","jbresyncthreshold","jbimpl","jblog");
$file="";
    $data = preg_split('~\s*;\s*~', $parameter,-1,PREG_SPLIT_NO_EMPTY);
    $max=count($data);
	foreach($options as $option => $value){
		for($count=0;$count<$max;$count++){
			$buff = preg_split('~\s*=\s*~', $data[$count]);
			if ($value==strtolower($buff[0])){ 
				$buff[0]="";
				$str = implode("=", $buff);
				$file.=$value." ".$str."\n";
				}
			}
	}
return $file;
}


if (file_exists($amp_conf['ASTETCDIR'].'/h323.conf')){
	$file = file($amp_conf['ASTETCDIR'].'/h323.conf');
	$out = fopen($amp_conf['ASTETCDIR'].'/h323.conf.buff',"w");
	$parameter="";
	if($file){
	    if($out){
		foreach ($file as $data){
		    if ($found == true){
			    $pos=strpos($data,";");
			    if ($pos === false){
				$found=H323InstallCheck($data);
				if($found) $parameter.=$data.";";
			    }else{
				$buff=substr($data,0,$pos+1);
				$found=H323InstallCheck($buff);
				if ($pos==0) $data=substr($data,$pos+1,strlen($data));
				elseif($found) $parameter.=substr($data,0,$pos+1).";";
			    }
			    if($found){
				    $data=";".$data;
				fwrite($out,$data);
			    }else{
				fwrite($out,$data);
			    }
		    }else{
			fwrite($out,$data);
			if (strpos($data,"[general]")!==false){
			fwrite($out,$name_conf);
			$found=true;
			}
		    }
		}
	    $parameter=";".preg_replace("/[\s]/","",$parameter);
	    fclose($out);
	    }
	}
	
    if(unlink($amp_conf['ASTETCDIR'].'/h323.conf')){
	if(rename ($amp_conf['ASTETCDIR'].'/h323.conf.buff',$amp_conf['ASTETCDIR'].'/h323.conf')){
	    $file = fopen($amp_conf['ASTETCDIR'].'/h323_additional.conf',"w");
	    if ($file){
		$data=$indication_warning;
		$data.=H323GetParameter($parameter);
		fwrite($file, $data);
		fclose($file);
	    }
	}
    }
}else{
    $file = fopen($amp_conf['ASTETCDIR'].'/h323.conf',"w");
    if ($file){
	$data=$indication_warning;
	$data.="; These files will all be included in the [general] context\n";
	$data.=$name_conf;
	fwrite($file, $data);
	fclose($file);
    } 
    $file = fopen($amp_conf['ASTETCDIR'].'/h323_additional.conf',"w");
    if ($file){
	$data=$indication_warning;
	$data.="[general]\n";
	$data.="port = 1720\n";
	fwrite($file, $data);
	fclose($file);
    }
}
?>
